name: deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - uses: w9jds/setup-firebase@main
        with:
          gcp_sa_key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EXAMTRAINING_C20CD }}
      - run: yarn
      - run: yarn build
      - run: |
          pushd packages/core && npm pack && popd
          cp packages/core/examtraining-core-1.0.0.tgz packages/functions
          tmp=$(mktemp)
          pushd packages/functions && jq '.dependencies."@examtraining/core" = "file:examtraining-core-1.0.0.tgz"' package.json > "$tmp" && mv "$tmp" package.json && popd
      - run: firebase deploy --only hosting
      - run: firebase deploy --only functions
